eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: comsume-client
feign:
  hystrix:
    enabled: true
management:
  endpoint:
    health:
      show-details: always
#想要的header加在配置文件中，要不调用链路时会屏蔽掉
#sensitive-headers: accessToken